# Synthwave Theme for Alacritty

[colors.primary]
background = "#0a0a1a"
foreground = "#00ffff"
dim_foreground = "#00cccc"
bright_foreground = "#00ffff"

[colors.cursor]
text = "#0a0a1a"
cursor = "#ff00ff"

[colors.vi_mode_cursor]
text = "#0a0a1a"
cursor = "#ffff00"

[colors.search.matches]
foreground = "#0a0a1a"
background = "#ff006f"

[colors.search.focused_match]
foreground = "#0a0a1a"
background = "#00ff00"

[colors.footer_bar]
foreground = "#0a0a1a"
background = "#ff00ff"

[colors.hints.start]
foreground = "#0a0a1a"
background = "#ffff00"

[colors.hints.end]
foreground = "#0a0a1a"
background = "#ff006f"

[colors.selection]
text = "#0a0a1a"
background = "#ff00ff"

[colors.normal]
black = "#16213e"
red = "#ff006f"
green = "#00ff00"
yellow = "#ffff00"
blue = "#0080ff"
magenta = "#ff00ff"
cyan = "#00ffff"
white = "#e0e0e0"

[colors.bright]
black = "#1f3a5f"
red = "#ff3388"
green = "#33ff33"
yellow = "#ffff66"
blue = "#3399ff"
magenta = "#ff66ff"
cyan = "#66ffff"
white = "#ffffff"

[colors.dim]
black = "#0d1929"
red = "#cc0056"
green = "#00cc00"
yellow = "#cccc00"
blue = "#0066cc"
magenta = "#cc00cc"
cyan = "#00cccc"
white = "#b0b0b0"

[[colors.indexed_colors]]
index = 16
color = "#ff8800"

[[colors.indexed_colors]]
index = 17
color = "#ff00aa"